// <auto-generated />
using System;
using BookStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    partial class BookStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStore.Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookPdfFileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Liam Moore",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\edad80b3-edfb-4984-979f-319bcbb96049_Head _First_C_Sharp.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\83522a32-aa0b-4bd6-a84a-9e5476a26ab5_1.png",
                            CreatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1041),
                            Description = "Head First C# is a complete learning experience for programming\r\nwith C#, XAML, the .NET Framework, and Visual Studio. Built for\r\nyour brain, this book keeps you engaged from the first chapter,\r\nwhere you’ll build a fully functional video game. After that, you’ll\r\nlearn about classes and object-oriented programming, draw graphics and animation, query your data with LINQ, and serialize it to\r\nfiles. And you’ll do it all by building games, solving puzzles, and\r\ndoing hands-on projects. By the time you’re done you’ll be a solid\r\nC# programmer, and you’ll have a great time along the way!",
                            LanguageId = 2,
                            Title = "Head First C#",
                            TotalPage = 681,
                            UpdatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1063)
                        },
                        new
                        {
                            Id = 2,
                            Author = "Mason Gonzalez",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\edad80b3-edfb-4984-979f-319bcbb96049_Head _First_C_Sharp.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\acbc0832-b6cb-4cbe-9fc8-ddd079389cbb_1.jpg",
                            CreatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1068),
                            Description = "The C++ Programming Language is a complete learning experience for programming\r\nwith C#, XAML, the .NET Framework, and Visual Studio. Built for\r\nyour brain, this book keeps you engaged from the first chapter,\r\nwhere you’ll build a fully functional video game. After that, you’ll\r\nlearn about classes and object-oriented programming, draw graphics and animation, query your data with LINQ, and serialize it to\r\nfiles. And you’ll do it all by building games, solving puzzles, and\r\ndoing hands-on projects. By the time you’re done you’ll be a solid\r\nC# programmer, and you’ll have a great time along the way!",
                            LanguageId = 1,
                            Title = "The C++ Programming Language",
                            TotalPage = 552,
                            UpdatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1068)
                        },
                        new
                        {
                            Id = 3,
                            Author = "Ava Taylor",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\edad80b3-edfb-4984-979f-319bcbb96049_Head _First_C_Sharp.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\fc4642a8-a8b3-4e43-9134-fd2cbae68af8_1.jpg",
                            CreatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1070),
                            Description = "Beginning Git and GitHub is a complete learning experience for programming\r\nwith C#, XAML, the .NET Framework, and Visual Studio. Built for\r\nyour brain, this book keeps you engaged from the first chapter,\r\nwhere you’ll build a fully functional video game. After that, you’ll\r\nlearn about classes and object-oriented programming, draw graphics and animation, query your data with LINQ, and serialize it to\r\nfiles. And you’ll do it all by building games, solving puzzles, and\r\ndoing hands-on projects. By the time you’re done you’ll be a solid\r\nC# programmer, and you’ll have a great time along the way!",
                            LanguageId = 1,
                            Title = "Beginning Git and GitHub",
                            TotalPage = 721,
                            UpdatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1070)
                        },
                        new
                        {
                            Id = 4,
                            Author = "Mariot Lee",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\edad80b3-edfb-4984-979f-319bcbb96049_Head _First_C_Sharp.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\1e15c7af-09d5-4484-9cf7-bbf4f4f706f3_1.jpg",
                            CreatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1111),
                            Description = "JavaScript for Web Developers is a complete learning experience for programming\r\nwith C#, XAML, the .NET Framework, and Visual Studio. Built for\r\nyour brain, this book keeps you engaged from the first chapter,\r\nwhere you’ll build a fully functional video game. After that, you’ll\r\nlearn about classes and object-oriented programming, draw graphics and animation, query your data with LINQ, and serialize it to\r\nfiles. And you’ll do it all by building games, solving puzzles, and\r\ndoing hands-on projects. By the time you’re done you’ll be a solid\r\nC# programmer, and you’ll have a great time along the way!",
                            LanguageId = 1,
                            Title = "JavaScript for Web Developers",
                            TotalPage = 220,
                            UpdatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1112)
                        },
                        new
                        {
                            Id = 5,
                            Author = "Mariot Garcia",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\edad80b3-edfb-4984-979f-319bcbb96049_Head _First_C_Sharp.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\359ee713-f716-488c-866d-d05c57bafc1b_1.jpg",
                            CreatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1113),
                            Description = "Python (All-In-One) For Dummies is a complete learning experience for programming\r\nwith C#, XAML, the .NET Framework, and Visual Studio. Built for\r\nyour brain, this book keeps you engaged from the first chapter,\r\nwhere you’ll build a fully functional video game. After that, you’ll\r\nlearn about classes and object-oriented programming, draw graphics and animation, query your data with LINQ, and serialize it to\r\nfiles. And you’ll do it all by building games, solving puzzles, and\r\ndoing hands-on projects. By the time you’re done you’ll be a solid\r\nC# programmer, and you’ll have a great time along the way!",
                            LanguageId = 1,
                            Title = "Python (All-In-One) For Dummies",
                            TotalPage = 723,
                            UpdatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1114)
                        },
                        new
                        {
                            Id = 6,
                            Author = "Olivia Miller",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\edad80b3-edfb-4984-979f-319bcbb96049_Head _First_C_Sharp.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\04734f18-dc2e-4ed5-bf47-5be69608dc9a_1.jpeg",
                            CreatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1122),
                            Description = "Head First Java is a complete learning experience for programming\r\nwith C#, XAML, the .NET Framework, and Visual Studio. Built for\r\nyour brain, this book keeps you engaged from the first chapter,\r\nwhere you’ll build a fully functional video game. After that, you’ll\r\nlearn about classes and object-oriented programming, draw graphics and animation, query your data with LINQ, and serialize it to\r\nfiles. And you’ll do it all by building games, solving puzzles, and\r\ndoing hands-on projects. By the time you’re done you’ll be a solid\r\nC# programmer, and you’ll have a great time along the way!",
                            LanguageId = 2,
                            Title = "Head First Java",
                            TotalPage = 281,
                            UpdatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1122)
                        },
                        new
                        {
                            Id = 7,
                            Author = "Elijah Smith",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\edad80b3-edfb-4984-979f-319bcbb96049_Head _First_C_Sharp.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\01fd088e-db1a-4e60-b6ef-ae96c2afddab_1.jpg",
                            CreatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1124),
                            Description = "Scala for the Impatient (Second Edition) is a complete learning experience for programming\r\nwith C#, XAML, the .NET Framework, and Visual Studio. Built for\r\nyour brain, this book keeps you engaged from the first chapter,\r\nwhere you’ll build a fully functional video game. After that, you’ll\r\nlearn about classes and object-oriented programming, draw graphics and animation, query your data with LINQ, and serialize it to\r\nfiles. And you’ll do it all by building games, solving puzzles, and\r\ndoing hands-on projects. By the time you’re done you’ll be a solid\r\nC# programmer, and you’ll have a great time along the way!",
                            LanguageId = 2,
                            Title = "Scala for the Impatient (Second Edition)",
                            TotalPage = 518,
                            UpdatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1124)
                        },
                        new
                        {
                            Id = 8,
                            Author = "Michael Harris",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\edad80b3-edfb-4984-979f-319bcbb96049_Head _First_C_Sharp.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\87b8a2c5-6f10-4443-9eb1-591e15f2b308_1.jpg",
                            CreatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1125),
                            Description = "Learn PHP 8 is a complete learning experience for programming\r\nwith C#, XAML, the .NET Framework, and Visual Studio. Built for\r\nyour brain, this book keeps you engaged from the first chapter,\r\nwhere you’ll build a fully functional video game. After that, you’ll\r\nlearn about classes and object-oriented programming, draw graphics and animation, query your data with LINQ, and serialize it to\r\nfiles. And you’ll do it all by building games, solving puzzles, and\r\ndoing hands-on projects. By the time you’re done you’ll be a solid\r\nC# programmer, and you’ll have a great time along the way!",
                            LanguageId = 1,
                            Title = "Learn PHP 8",
                            TotalPage = 208,
                            UpdatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1126)
                        },
                        new
                        {
                            Id = 9,
                            Author = "Emma Thompson",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\edad80b3-edfb-4984-979f-319bcbb96049_Head _First_C_Sharp.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\a2eedf17-f1d1-4094-a141-fa8b42997f2a_1.jpg",
                            CreatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1150),
                            Description = "Kotlin In Action is a complete learning experience for programming\r\nwith C#, XAML, the .NET Framework, and Visual Studio. Built for\r\nyour brain, this book keeps you engaged from the first chapter,\r\nwhere you’ll build a fully functional video game. After that, you’ll\r\nlearn about classes and object-oriented programming, draw graphics and animation, query your data with LINQ, and serialize it to\r\nfiles. And you’ll do it all by building games, solving puzzles, and\r\ndoing hands-on projects. By the time you’re done you’ll be a solid\r\nC# programmer, and you’ll have a great time along the way!",
                            LanguageId = 1,
                            Title = "Kotlin In Action",
                            TotalPage = 111,
                            UpdatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1150)
                        },
                        new
                        {
                            Id = 10,
                            Author = "Kathy Harris",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\edad80b3-edfb-4984-979f-319bcbb96049_Head _First_C_Sharp.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\648c38b8-0ed4-4674-a9e5-c5d623063e95_1.jpg",
                            CreatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1153),
                            Description = "Head First Swift is a complete learning experience for programming\r\nwith C#, XAML, the .NET Framework, and Visual Studio. Built for\r\nyour brain, this book keeps you engaged from the first chapter,\r\nwhere you’ll build a fully functional video game. After that, you’ll\r\nlearn about classes and object-oriented programming, draw graphics and animation, query your data with LINQ, and serialize it to\r\nfiles. And you’ll do it all by building games, solving puzzles, and\r\ndoing hands-on projects. By the time you’re done you’ll be a solid\r\nC# programmer, and you’ll have a great time along the way!",
                            LanguageId = 1,
                            Title = "Head First Swift",
                            TotalPage = 662,
                            UpdatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1153)
                        },
                        new
                        {
                            Id = 11,
                            Author = "William Hernandez",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\edad80b3-edfb-4984-979f-319bcbb96049_Head _First_C_Sharp.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\1e15c7af-09d5-4484-9cf7-bbf4f4f706f3bb.jpg",
                            CreatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1155),
                            Description = "Emotional Intelligence is a complete learning experience for programming\r\nwith C#, XAML, the .NET Framework, and Visual Studio. Built for\r\nyour brain, this book keeps you engaged from the first chapter,\r\nwhere you’ll build a fully functional video game. After that, you’ll\r\nlearn about classes and object-oriented programming, draw graphics and animation, query your data with LINQ, and serialize it to\r\nfiles. And you’ll do it all by building games, solving puzzles, and\r\ndoing hands-on projects. By the time you’re done you’ll be a solid\r\nC# programmer, and you’ll have a great time along the way!",
                            LanguageId = 1,
                            Title = "Emotional Intelligence",
                            TotalPage = 151,
                            UpdatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1155)
                        },
                        new
                        {
                            Id = 12,
                            Author = "Michael Jackson",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\edad80b3-edfb-4984-979f-319bcbb96049_Head _First_C_Sharp.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\1e15c7af-09d5-4484-9cf7-bbf4f4f706f555.jpg",
                            CreatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1157),
                            Description = "Dark Psychology is a complete learning experience for programming\r\nwith C#, XAML, the .NET Framework, and Visual Studio. Built for\r\nyour brain, this book keeps you engaged from the first chapter,\r\nwhere you’ll build a fully functional video game. After that, you’ll\r\nlearn about classes and object-oriented programming, draw graphics and animation, query your data with LINQ, and serialize it to\r\nfiles. And you’ll do it all by building games, solving puzzles, and\r\ndoing hands-on projects. By the time you’re done you’ll be a solid\r\nC# programmer, and you’ll have a great time along the way!",
                            LanguageId = 2,
                            Title = "Dark Psychology",
                            TotalPage = 547,
                            UpdatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1157)
                        },
                        new
                        {
                            Id = 13,
                            Author = "Isabella Martinez",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\edad80b3-edfb-4984-979f-319bcbb96049_Head _First_C_Sharp.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\1e15c7af-09d5-4484-9cf7-bbf4f4f706f333.jpg",
                            CreatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1159),
                            Description = "Emotional Intelligence (Why It Can Matter More Than IQ) is a complete learning experience for programming\r\nwith C#, XAML, the .NET Framework, and Visual Studio. Built for\r\nyour brain, this book keeps you engaged from the first chapter,\r\nwhere you’ll build a fully functional video game. After that, you’ll\r\nlearn about classes and object-oriented programming, draw graphics and animation, query your data with LINQ, and serialize it to\r\nfiles. And you’ll do it all by building games, solving puzzles, and\r\ndoing hands-on projects. By the time you’re done you’ll be a solid\r\nC# programmer, and you’ll have a great time along the way!",
                            LanguageId = 2,
                            Title = "Emotional Intelligence (Why It Can Matter More Than IQ)",
                            TotalPage = 318,
                            UpdatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1159)
                        },
                        new
                        {
                            Id = 14,
                            Author = "Matt Miller",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\edad80b3-edfb-4984-979f-319bcbb96049_Head _First_C_Sharp.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\1e15c7af-09d5-4484-9cf7-hho4f4f706f3bb.webp",
                            CreatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1179),
                            Description = "The Emotional Intelligence workbook is a complete learning experience for programming\r\nwith C#, XAML, the .NET Framework, and Visual Studio. Built for\r\nyour brain, this book keeps you engaged from the first chapter,\r\nwhere you’ll build a fully functional video game. After that, you’ll\r\nlearn about classes and object-oriented programming, draw graphics and animation, query your data with LINQ, and serialize it to\r\nfiles. And you’ll do it all by building games, solving puzzles, and\r\ndoing hands-on projects. By the time you’re done you’ll be a solid\r\nC# programmer, and you’ll have a great time along the way!",
                            LanguageId = 2,
                            Title = "The Emotional Intelligence workbook",
                            TotalPage = 579,
                            UpdatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1179)
                        },
                        new
                        {
                            Id = 15,
                            Author = "Mia Rodriguez",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\edad80b3-edfb-4984-979f-319bcbb96049_Head _First_C_Sharp.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\1e15c7af-09d5-4484-9cf7-7bf4f3f706f3fb.jpg",
                            CreatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1181),
                            Description = "Emotional Intelligence (for leadership) is a complete learning experience for programming\r\nwith C#, XAML, the .NET Framework, and Visual Studio. Built for\r\nyour brain, this book keeps you engaged from the first chapter,\r\nwhere you’ll build a fully functional video game. After that, you’ll\r\nlearn about classes and object-oriented programming, draw graphics and animation, query your data with LINQ, and serialize it to\r\nfiles. And you’ll do it all by building games, solving puzzles, and\r\ndoing hands-on projects. By the time you’re done you’ll be a solid\r\nC# programmer, and you’ll have a great time along the way!",
                            LanguageId = 2,
                            Title = "Emotional Intelligence (for leadership)",
                            TotalPage = 667,
                            UpdatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1181)
                        },
                        new
                        {
                            Id = 16,
                            Author = "James Martinez",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\edad80b3-edfb-4984-979f-319bcbb96049_Head _First_C_Sharp.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\acbc0832-b6cb-4cbe-9gc8-ddd079389cbb_1.jpg",
                            CreatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1183),
                            Description = "Take What You Need is a complete learning experience for programming\r\nwith C#, XAML, the .NET Framework, and Visual Studio. Built for\r\nyour brain, this book keeps you engaged from the first chapter,\r\nwhere you’ll build a fully functional video game. After that, you’ll\r\nlearn about classes and object-oriented programming, draw graphics and animation, query your data with LINQ, and serialize it to\r\nfiles. And you’ll do it all by building games, solving puzzles, and\r\ndoing hands-on projects. By the time you’re done you’ll be a solid\r\nC# programmer, and you’ll have a great time along the way!",
                            LanguageId = 1,
                            Title = "Take What You Need",
                            TotalPage = 440,
                            UpdatedOn = new DateTime(2023, 4, 7, 11, 44, 14, 873, DateTimeKind.Local).AddTicks(1183)
                        });
                });

            modelBuilder.Entity("BookStore.Data.BookGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookGalleries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\coverImages\\83522a32-aa0b-4bd6-a84a-9e5476a26ab5_1.png"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4b77-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 1,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4bd7-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 4,
                            BookId = 1,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\ce0f7196-f93d-4de6-85e7-f1ed076b4aaa_2.png"
                        },
                        new
                        {
                            Id = 5,
                            BookId = 2,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\coverImages\\acbc0832-b6cb-4cbe-9fc8-ddd079389cbb_1.jpg"
                        },
                        new
                        {
                            Id = 6,
                            BookId = 2,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4b77-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 7,
                            BookId = 2,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4bd7-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 8,
                            BookId = 2,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\ce0f7196-f93d-4de6-85e7-f1ed076b4aaa_2.png"
                        },
                        new
                        {
                            Id = 9,
                            BookId = 3,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\coverImages\\fc4642a8-a8b3-4e43-9134-fd2cbae68af8_1.jpg"
                        },
                        new
                        {
                            Id = 10,
                            BookId = 3,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4b77-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 11,
                            BookId = 3,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4bd7-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 12,
                            BookId = 3,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\ce0f7196-f93d-4de6-85e7-f1ed076b4aaa_2.png"
                        },
                        new
                        {
                            Id = 13,
                            BookId = 4,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\coverImages\\1e15c7af-09d5-4484-9cf7-bbf4f4f706f3_1.jpg"
                        },
                        new
                        {
                            Id = 14,
                            BookId = 4,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4b77-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 15,
                            BookId = 4,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4bd7-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 16,
                            BookId = 4,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\ce0f7196-f93d-4de6-85e7-f1ed076b4aaa_2.png"
                        },
                        new
                        {
                            Id = 17,
                            BookId = 5,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\coverImages\\359ee713-f716-488c-866d-d05c57bafc1b_1.jpg"
                        },
                        new
                        {
                            Id = 18,
                            BookId = 5,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4b77-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 19,
                            BookId = 5,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4bd7-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 20,
                            BookId = 5,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\ce0f7196-f93d-4de6-85e7-f1ed076b4aaa_2.png"
                        },
                        new
                        {
                            Id = 21,
                            BookId = 6,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\coverImages\\04734f18-dc2e-4ed5-bf47-5be69608dc9a_1.jpeg"
                        },
                        new
                        {
                            Id = 22,
                            BookId = 6,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4b77-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 23,
                            BookId = 6,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4bd7-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 24,
                            BookId = 6,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\ce0f7196-f93d-4de6-85e7-f1ed076b4aaa_2.png"
                        },
                        new
                        {
                            Id = 25,
                            BookId = 7,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\coverImages\\01fd088e-db1a-4e60-b6ef-ae96c2afddab_1.jpg"
                        },
                        new
                        {
                            Id = 26,
                            BookId = 7,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4b77-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 27,
                            BookId = 7,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4bd7-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 28,
                            BookId = 7,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\ce0f7196-f93d-4de6-85e7-f1ed076b4aaa_2.png"
                        },
                        new
                        {
                            Id = 29,
                            BookId = 8,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\coverImages\\87b8a2c5-6f10-4443-9eb1-591e15f2b308_1.jpg"
                        },
                        new
                        {
                            Id = 30,
                            BookId = 8,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4b77-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 31,
                            BookId = 8,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4bd7-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 32,
                            BookId = 8,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\ce0f7196-f93d-4de6-85e7-f1ed076b4aaa_2.png"
                        },
                        new
                        {
                            Id = 33,
                            BookId = 9,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\coverImages\\a2eedf17-f1d1-4094-a141-fa8b42997f2a_1.jpg"
                        },
                        new
                        {
                            Id = 34,
                            BookId = 9,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4b77-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 35,
                            BookId = 9,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4bd7-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 36,
                            BookId = 9,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\ce0f7196-f93d-4de6-85e7-f1ed076b4aaa_2.png"
                        },
                        new
                        {
                            Id = 37,
                            BookId = 10,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\coverImages\\648c38b8-0ed4-4674-a9e5-c5d623063e95_1.jpg"
                        },
                        new
                        {
                            Id = 38,
                            BookId = 10,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4b77-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 39,
                            BookId = 10,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4bd7-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 40,
                            BookId = 10,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\ce0f7196-f93d-4de6-85e7-f1ed076b4aaa_2.png"
                        },
                        new
                        {
                            Id = 41,
                            BookId = 11,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\coverImages\\1e15c7af-09d5-4484-9cf7-bbf4f4f706f3bb.jpg"
                        },
                        new
                        {
                            Id = 42,
                            BookId = 11,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4b77-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 43,
                            BookId = 11,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4bd7-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 44,
                            BookId = 11,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\ce0f7196-f93d-4de6-85e7-f1ed076b4aaa_2.png"
                        },
                        new
                        {
                            Id = 45,
                            BookId = 12,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\coverImages\\1e15c7af-09d5-4484-9cf7-bbf4f4f706f555.jpg"
                        },
                        new
                        {
                            Id = 46,
                            BookId = 12,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4b77-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 47,
                            BookId = 12,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4bd7-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 48,
                            BookId = 12,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\ce0f7196-f93d-4de6-85e7-f1ed076b4aaa_2.png"
                        },
                        new
                        {
                            Id = 49,
                            BookId = 13,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\coverImages\\1e15c7af-09d5-4484-9cf7-bbf4f4f706f333.jpg"
                        },
                        new
                        {
                            Id = 50,
                            BookId = 13,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4b77-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 51,
                            BookId = 13,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4bd7-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 52,
                            BookId = 13,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\ce0f7196-f93d-4de6-85e7-f1ed076b4aaa_2.png"
                        },
                        new
                        {
                            Id = 53,
                            BookId = 14,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\coverImages\\1e15c7af-09d5-4484-9cf7-hho4f4f706f3bb.webp"
                        },
                        new
                        {
                            Id = 54,
                            BookId = 14,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4b77-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 55,
                            BookId = 14,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4bd7-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 56,
                            BookId = 14,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\ce0f7196-f93d-4de6-85e7-f1ed076b4aaa_2.png"
                        },
                        new
                        {
                            Id = 57,
                            BookId = 15,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\coverImages\\1e15c7af-09d5-4484-9cf7-7bf4f3f706f3fb.jpg"
                        },
                        new
                        {
                            Id = 58,
                            BookId = 15,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4b77-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 59,
                            BookId = 15,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4bd7-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 60,
                            BookId = 15,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\ce0f7196-f93d-4de6-85e7-f1ed076b4aaa_2.png"
                        },
                        new
                        {
                            Id = 61,
                            BookId = 16,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\coverImages\\acbc0832-b6cb-4cbe-9gc8-ddd079389cbb_1.jpg"
                        },
                        new
                        {
                            Id = 62,
                            BookId = 16,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4b77-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 63,
                            BookId = 16,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4bd7-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 64,
                            BookId = 16,
                            Name = "X.jpeg",
                            URL = "\\files\\books\\galleryImages\\ce0f7196-f93d-4de6-85e7-f1ed076b4aaa_2.png"
                        });
                });

            modelBuilder.Entity("BookStore.Data.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Name = "German"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Russian"
                        });
                });

            modelBuilder.Entity("BookStore.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c3bdd301-35d1-4114-b5e4-78d509b5607c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aea37ab2-e094-430e-a4f8-cf6f057dd221",
                            Email = "edzaryan@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Edgar",
                            LastName = "Yeghiazaryan",
                            LockoutEnabled = true,
                            NormalizedEmail = "EDZARYAN@GMAIL.COM",
                            NormalizedUserName = "EDZARYAN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE0bcGEnzC/j5TL0/jEDsnSgV4z/pv1hlrmfmR/VqDXLfADbhYIW1pHX6/njIJ0AVA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9d5807a0-86fe-4a61-85f1-6c739241b150",
                            TwoFactorEnabled = false,
                            UserName = "edzaryan@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "bc6f72c0-66aa-4ec9-adb3-fba947bd0014",
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "ff6f72c0-66aa-4ec9-adb3-fba947bd0014",
                            ConcurrencyStamp = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "c3bdd301-35d1-4114-b5e4-78d509b5607c",
                            RoleId = "bc6f72c0-66aa-4ec9-adb3-fba947bd0014"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BookStore.Data.Book", b =>
                {
                    b.HasOne("BookStore.Data.Language", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("BookStore.Data.BookGallery", b =>
                {
                    b.HasOne("BookStore.Data.Book", "Book")
                        .WithMany("bookGallery")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BookStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BookStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BookStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Data.Book", b =>
                {
                    b.Navigation("bookGallery");
                });

            modelBuilder.Entity("BookStore.Data.Language", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
