// <auto-generated />
using System;
using BookStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    partial class BookStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStore.Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookPdfFileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Andrew Stellman",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\edad80b3-edfb-4984-979f-319bcbb96049_Head _First_C_Sharp.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\83522a32-aa0b-4bd6-a84a-9e5476a26ab5_1.png",
                            CreatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6352),
                            Description = "Head First C# is a complete learning experience for programming\r\nwith C#, XAML, the .NET Framework, and Visual Studio. Built for\r\nyour brain, this book keeps you engaged from the first chapter,\r\nwhere you’ll build a fully functional video game. After that, you’ll\r\nlearn about classes and object-oriented programming, draw graphics and animation, query your data with LINQ, and serialize it to\r\nfiles. And you’ll do it all by building games, solving puzzles, and\r\ndoing hands-on projects. By the time you’re done you’ll be a solid\r\nC# programmer, and you’ll have a great time along the way!",
                            LanguageId = 1,
                            Title = "Head First C#",
                            TotalPage = 194,
                            UpdatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6370)
                        },
                        new
                        {
                            Id = 2,
                            Author = "Bjarne Straustrup",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\29eac4b2-b4bb-495c-b3c4-f5c01768e81f_11.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\acbc0832-b6cb-4cbe-9fc8-ddd079389cbb_1.jpg",
                            CreatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6372),
                            Description = "The new C++11 standard allows programmers to express ideas more clearly, simply, and directly, and to write faster, more efficient code. Bjarne Stroustrup, the designer and original implementer of C++, has reorganized, extended, and completely rewritten his definitive reference and tutorial for programmers who want to use C++ most effectively.",
                            LanguageId = 1,
                            Title = "The C++ Programming Language",
                            TotalPage = 1366,
                            UpdatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6373)
                        },
                        new
                        {
                            Id = 3,
                            Author = "Mariot Tsitoara",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\01b97c2c-7062-478e-b0e9-8b117cc10fbe_Beginning_Git_and_GitHub_(2020).pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\fc4642a8-a8b3-4e43-9134-fd2cbae68af8_1.jpg",
                            CreatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6375),
                            Description = "Divided into three parts – Version Control, Project Management and Teamwork – this book reveals what waits for you in the real world and how to resolve the problems you may run into. Once past the basics of Git, you'll see how to manage a software project, and finally how to utilize Git and GithHub to work effectively as a team.",
                            LanguageId = 1,
                            Title = "Beginning Git and GitHub",
                            TotalPage = 294,
                            UpdatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6375)
                        },
                        new
                        {
                            Id = 4,
                            Author = "Matt Frisbie",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\7c64fba0-1b7a-46bc-9403-a759bcbf23ea_Beginning_Git_and_GitHub_(2020).pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\1e15c7af-09d5-4484-9cf7-bbf4f4f706f3_1.jpg",
                            CreatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6377),
                            Description = "Professional JavaScript for Web Developers is the essential guide to next-level JavaScript development. At 1,200 pages, this book is the most comprehensive JavaScript reference available anywhere. Written for intermediate-to-advanced programmers, this book jumps right into the technical details to help you clean up your code and become a more sophisticated JavaScript developer. ",
                            LanguageId = 1,
                            Title = "JavaScript for Web Developers",
                            TotalPage = 964,
                            UpdatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6377)
                        },
                        new
                        {
                            Id = 5,
                            Author = "John C. Shovic",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\a8a0c944-d076-436d-8980-e8d228482a47_Python_All-In-One_for_Dummies.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\359ee713-f716-488c-866d-d05c57bafc1b_1.jpg",
                            CreatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6379),
                            Description = "This book is a reference manual to guide you through the process of learning\r\nPython and how to use it in modern computer applications, such as data science,\r\nartificial intelligence, physical computing, and robotics. If you’re looking to learn\r\na little about a lot of exciting things, this is the book for you. It gives you an introduction to the topics that you’ll need to explore more deeply.",
                            LanguageId = 1,
                            Title = "Python (All-In-One) For Dummies",
                            TotalPage = 723,
                            UpdatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6379)
                        },
                        new
                        {
                            Id = 6,
                            Author = "Kathy Sierra",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\59b685ea-9a6a-4bf5-be00-35d2e884f6ed_Head_First_Java_Second_Edition.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\04734f18-dc2e-4ed5-bf47-5be69608dc9a_1.jpeg",
                            CreatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6381),
                            Description = "Head First Java is a complete learning experience in Java and object-oriented programming. With this book, you'll learn the Java language with a unique method that goes beyond how-to manuals and helps you become a great programmer. Through puzzles, mysteries, and soul-searching interviews with famous Java objects, you'll quickly get up to speed on Java's fundamentals and advanced topics including lambdas, streams, generics, threading, networking, and the dreaded desktop GUI.",
                            LanguageId = 1,
                            Title = "Head First Java",
                            TotalPage = 722,
                            UpdatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6381)
                        },
                        new
                        {
                            Id = 7,
                            Author = "Cay S. Horstmann",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\6dbbb0b0-59ec-4820-9422-e4df9a3241c8_Scala for the Impatient, 2nd Edition.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\01fd088e-db1a-4e60-b6ef-ae96c2afddab_1.jpg",
                            CreatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6383),
                            Description = "Interest in the Scala programming language continues to grow for many reasons. Scala embraces the functional programming style without abandoning the object-oriented paradigm, and it allows you to write programs more concisely than in Java. Because Scala runs on the JVM, it can access any Java library and is interoperable with familiar Java frameworks. Scala also makes it easier to leverage the full power of concurrency.",
                            LanguageId = 1,
                            Title = "Scala for the Impatient (Second Edition)",
                            TotalPage = 385,
                            UpdatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6383)
                        },
                        new
                        {
                            Id = 8,
                            Author = "Steve Prettyman",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\1557c693-f85a-4d23-bfeb-d73933b698c8_Learn_PHP_8_2nd_Edition_(2020).pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\87b8a2c5-6f10-4443-9eb1-591e15f2b308_1.jpg",
                            CreatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6385),
                            Description = "Write solid, secure, object-oriented code in the new PHP 8. In this book you will create a complete three-tier application using a natural process of building and testing modules within each tier. This practical approach teaches you about app development and introduces PHP features when they are actually needed rather than providing you with abstract theory and contrived examples.",
                            LanguageId = 1,
                            Title = "Learn PHP 8",
                            TotalPage = 422,
                            UpdatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6387)
                        },
                        new
                        {
                            Id = 9,
                            Author = "Dmitry Jemerov",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\bcd7faf8-e2c0-4f64-895a-c26c00acdd14_Kotlin_in_Action_(2017).pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\a224595a-1dbf-4240-992e-859f6a287cfa_1.jpg",
                            CreatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6389),
                            Description = "Kotllyn became interested in Android as an official language. This book is a kind of official book written by developers of Comlin compilers in JetBrain who developed the language. The greatest feature of the Kohlin language is its practicality. This book was also used to emphasize practicality. Introduce Kotllyns fundamentals and explain the contents of higher order functions, object orientation, and generics.",
                            LanguageId = 1,
                            Title = "Kotlin In Action",
                            TotalPage = 363,
                            UpdatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6389)
                        },
                        new
                        {
                            Id = 10,
                            Author = "Paris Buttfield-Addison",
                            BookPdfFileUrl = "\\files\\books\\bookPdfFiles\\5c399598-3a58-4efd-b67c-a4f55303ffcf_Paris_Buttfield-Addison_Jon_Manning_-_Head_First_Swift_2022.pdf",
                            CoverImageUrl = "\\files\\books\\coverImages\\e021b60d-5c7c-4a59-96d3-32bcf10bccb2_1491922850.01._SCLZZZZZZZ_SX500_.jpg",
                            CreatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6391),
                            Description = "Swift is best known as Apple's programming language of choice for developing apps on iOS, iPadOS, macOS, watchOS, and tvOS. But it's far more versatile than that. Open source Swift is also gaining ground as a language for systems programming and server-side code, and it runs on Linux and Windows. So where do you start? With Head First Swift, you'll explore from the ground ",
                            LanguageId = 1,
                            Title = "Head First Swift",
                            TotalPage = 722,
                            UpdatedOn = new DateTime(2023, 4, 1, 23, 41, 19, 204, DateTimeKind.Local).AddTicks(6391)
                        });
                });

            modelBuilder.Entity("BookStore.Data.BookGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookGalleries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Name = "5.jpeg",
                            URL = "\\files\\books\\coverImages\\83522a32-aa0b-4bd6-a84a-9e5476a26ab5_1.png"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            Name = "2.jpg",
                            URL = "\\files\\books\\galleryImages\\ce0f7196-f93d-4de6-85e7-f1ed076b4edc_2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 1,
                            Name = "3.png",
                            URL = "\\files\\books\\galleryImages\\45f78393-ca6c-4b77-b9cb-9e4120a9619d_3.png"
                        },
                        new
                        {
                            Id = 4,
                            BookId = 1,
                            Name = "4.jpeg",
                            URL = "\\files\\books\\galleryImages\\8a053ea6-0e24-4347-a98c-5cc61f432c23_4.jpeg"
                        },
                        new
                        {
                            Id = 5,
                            BookId = 2,
                            Name = "4.jpeg",
                            URL = "\\files\\books\\coverImages\\acbc0832-b6cb-4cbe-9fc8-ddd079389cbb_1.jpg"
                        },
                        new
                        {
                            Id = 6,
                            BookId = 2,
                            Name = "2.jpg",
                            URL = "\\files\\books\\galleryImages\\c04c92d7-e7cc-4a1e-bd1f-14db83cc9520_2.jpg"
                        },
                        new
                        {
                            Id = 7,
                            BookId = 2,
                            Name = "3.png",
                            URL = "\\files\\books\\galleryImages\\585eb055-1a37-4e0f-9706-47c99c544370_3.jpg"
                        },
                        new
                        {
                            Id = 8,
                            BookId = 2,
                            Name = "4.jpeg",
                            URL = "\\files\\books\\galleryImages\\535e6d66-6017-415a-8d1d-caf963b59f67_4.jpg"
                        },
                        new
                        {
                            Id = 9,
                            BookId = 3,
                            Name = "2.jpg",
                            URL = "\\files\\books\\coverImages\\1a059024-fb6e-410d-85db-963ba3f455b4_1.jpg"
                        },
                        new
                        {
                            Id = 10,
                            BookId = 3,
                            Name = "2.jpg",
                            URL = "\\files\\books\\galleryImages\\aaacf5f4-0b5d-4739-a44d-890065632f28_2.jpg"
                        },
                        new
                        {
                            Id = 11,
                            BookId = 3,
                            Name = "3.jpeg",
                            URL = "\\files\\books\\galleryImages\\f9015d77-3237-45d5-944b-ac864e9b15b6_3.jpeg"
                        },
                        new
                        {
                            Id = 12,
                            BookId = 3,
                            Name = "4.jpeg",
                            URL = "\\files\\books\\galleryImages\\6383ad9a-09eb-41dd-9e8a-02fbc7bd5ff9_4.jpeg"
                        },
                        new
                        {
                            Id = 13,
                            BookId = 4,
                            Name = "2.jpg",
                            URL = "\\files\\books\\coverImages\\1e15c7af-09d5-4484-9cf7-bbf4f4f706f3_1.jpg"
                        },
                        new
                        {
                            Id = 14,
                            BookId = 4,
                            Name = "2.jpg",
                            URL = "\\files\\books\\galleryImages\\2a12c3b8-9cf9-4d90-b8b7-720daf74adf8_2.jpg"
                        },
                        new
                        {
                            Id = 15,
                            BookId = 4,
                            Name = "3.jpeg",
                            URL = "\\files\\books\\galleryImages\\48d42e20-5ef0-43a6-9361-39e4083ffe04_3.jpeg"
                        },
                        new
                        {
                            Id = 16,
                            BookId = 4,
                            Name = "4.jpeg",
                            URL = "\\files\\books\\galleryImages\\9a2c740e-3bfa-463e-9e31-35294a695aba_4.jpeg"
                        },
                        new
                        {
                            Id = 17,
                            BookId = 5,
                            Name = "2.jpg",
                            URL = "\\files\\books\\coverImages\\359ee713-f716-488c-866d-d05c57bafc1b_1.jpg"
                        },
                        new
                        {
                            Id = 18,
                            BookId = 5,
                            Name = "2.jpg",
                            URL = "\\files\\books\\galleryImages\\aed2fbf7-5c53-41ef-8c65-7c0bb0210cd1_2.jpg"
                        },
                        new
                        {
                            Id = 19,
                            BookId = 5,
                            Name = "3.jpeg",
                            URL = "\\files\\books\\galleryImages\\b147163d-b9e6-4e5d-bc26-6f347300f547_3.jpeg"
                        },
                        new
                        {
                            Id = 20,
                            BookId = 5,
                            Name = "4.jpeg",
                            URL = "\\files\\books\\galleryImages\\3287bb6c-d76a-4e39-9baa-59ebdc8665f1_4.jpeg"
                        },
                        new
                        {
                            Id = 21,
                            BookId = 6,
                            Name = "2.jpg",
                            URL = "\\files\\books\\coverImages\\04734f18-dc2e-4ed5-bf47-5be69608dc9a_1.jpeg"
                        },
                        new
                        {
                            Id = 22,
                            BookId = 6,
                            Name = "2.jpg",
                            URL = "\\files\\books\\galleryImages\\af854ea4-84b7-4217-993b-49ac92492974_2.jpg"
                        },
                        new
                        {
                            Id = 23,
                            BookId = 6,
                            Name = "3.jpeg",
                            URL = "\\files\\books\\galleryImages\\470046f5-b2bc-4e17-834b-33624f300efd_3.jpeg"
                        },
                        new
                        {
                            Id = 24,
                            BookId = 6,
                            Name = "4.jpeg",
                            URL = "\\files\\books\\galleryImages\\874c31e5-93d3-4c89-80e9-ac0fa9cdbd1a_4.jpeg"
                        },
                        new
                        {
                            Id = 25,
                            BookId = 7,
                            Name = "1.jpeg",
                            URL = "\\files\\books\\galleryImages\\f2954d2c-94e0-4b0a-adce-058ed70d5b32_1.jpg"
                        },
                        new
                        {
                            Id = 26,
                            BookId = 7,
                            Name = "2.jpeg",
                            URL = "\\files\\books\\galleryImages\\a3d7d206-f541-4c90-8fb9-5320d572ef20_2.jpg"
                        },
                        new
                        {
                            Id = 27,
                            BookId = 7,
                            Name = "3.jpeg",
                            URL = "\\files\\books\\galleryImages\\968128e9-574e-4318-a582-53964dcafcd6_3.jpeg"
                        },
                        new
                        {
                            Id = 28,
                            BookId = 7,
                            Name = "4.jpeg",
                            URL = "\\files\\books\\galleryImages\\7ec06f14-5f08-419f-9900-ebaf7db8ceb1_4.jpeg"
                        },
                        new
                        {
                            Id = 29,
                            BookId = 8,
                            Name = "1.jpg",
                            URL = "\\files\\books\\galleryImages\\6004d2f5-8fc5-4fbc-8c63-c82367c9cb31_1.jpg"
                        },
                        new
                        {
                            Id = 30,
                            BookId = 8,
                            Name = "2.jpg",
                            URL = "\\files\\books\\galleryImages\\3287bb6c-d76a-4e39-9baa-59ebdc8665f1_4.jpeg"
                        },
                        new
                        {
                            Id = 31,
                            BookId = 8,
                            Name = "3.jpeg",
                            URL = "\\files\\books\\galleryImages\\470046f5-b2bc-4e17-834b-33624f300efd_3.jpeg"
                        },
                        new
                        {
                            Id = 32,
                            BookId = 8,
                            Name = "4.jpeg",
                            URL = "\\files\\books\\galleryImages\\edbe5e93-1536-48ca-8b44-846fd4b490ab_2.jpg"
                        },
                        new
                        {
                            Id = 33,
                            BookId = 9,
                            Name = "1.jpg",
                            URL = "\\files\\books\\galleryImages\\a2eedf17-f1d1-4094-a141-fa8b42997f2a_1.jpg"
                        },
                        new
                        {
                            Id = 34,
                            BookId = 9,
                            Name = "2.jpg",
                            URL = "\\files\\books\\galleryImages\\2c7328fe-1974-47af-a82f-ae25cf60e206_4.jpeg"
                        },
                        new
                        {
                            Id = 35,
                            BookId = 9,
                            Name = "3.jpeg",
                            URL = "\\files\\books\\galleryImages\\af854ea4-84b7-4217-993b-49ac92492974_2.jpg"
                        },
                        new
                        {
                            Id = 36,
                            BookId = 9,
                            Name = "4.jpeg",
                            URL = "\\files\\books\\galleryImages\\9a1b90d9-6a61-45d9-b015-dff9af9f2051_2.jpg"
                        },
                        new
                        {
                            Id = 37,
                            BookId = 10,
                            Name = "1.jpg",
                            URL = "\\files\\books\\galleryImages\\648c38b8-0ed4-4674-a9e5-c5d623063e95_1.webp"
                        },
                        new
                        {
                            Id = 38,
                            BookId = 10,
                            Name = "2.jpg",
                            URL = "\\files\\books\\galleryImages\\8a053ea6-0e24-4347-a98c-5cc61f432c23_4.jpeg"
                        },
                        new
                        {
                            Id = 39,
                            BookId = 10,
                            Name = "3.jpeg",
                            URL = "\\files\\books\\galleryImages\\535e6d66-6017-415a-8d1d-caf963b59f67_4.jpg"
                        },
                        new
                        {
                            Id = 40,
                            BookId = 10,
                            Name = "4.jpeg",
                            URL = "\\files\\books\\galleryImages\\23194214-9443-468c-8fbc-ccb417b7a204_3.webp"
                        });
                });

            modelBuilder.Entity("BookStore.Data.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Name = "German"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Russian"
                        });
                });

            modelBuilder.Entity("BookStore.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BookStore.Data.Book", b =>
                {
                    b.HasOne("BookStore.Data.Language", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("BookStore.Data.BookGallery", b =>
                {
                    b.HasOne("BookStore.Data.Book", "Book")
                        .WithMany("bookGallery")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BookStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BookStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BookStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Data.Book", b =>
                {
                    b.Navigation("bookGallery");
                });

            modelBuilder.Entity("BookStore.Data.Language", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
